markdown: redcarpet
highlighter: pygments

title_tag_text: cadigatt, mobile software
h1_tag_text: "Roman Nums"

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]

title: cadigatt
email: "info@cadigatt.com"
twitter: "cadigatt"


relative_permalinks: false
