markdown: redcarpet
highlighter: pygments

title_tag_text: cadigatt, mobile software
h1_tag_text: cadigatt

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
